use serde::Serialize;

/// Defines Zero-Sized Types (ZSTs) for tag signatures and implements
/// the `From` trait to convert them into their runtime `TagSignature` enum variant.
/// This is used when adding a TagValue into the Profile's tag map, using the with_tag method, which uses
/// a TagSignature as key, and a TagType instance as value.
macro_rules! define_tag_zsts {
    // The macro accepts one or more comma-separated identifiers.
    ($($zst_name:ident),+ $(,)?) => {
        // The `$(...)+` block repeats the implementation for each identifier provided.
        $(
            #[doc = concat!("A Zero-Sized Type representing the `", stringify!($zst_name), "` tag signature.")]
            #[derive(Default, Copy, Clone, Debug, PartialEq, Eq)]
            pub struct $zst_name;

            impl From<$zst_name> for TagSignature {
                fn from(_: $zst_name) -> Self {
                    TagSignature::$zst_name
                }
            }
        )+
    };
}

// Use the macro to generate all the ZSTs and their impls
define_tag_zsts!(
    AToB0Tag,
    AToB1Tag,
    AToB2Tag,
    AToB3Tag,
    AToM0Tag,
    BlueMatrixColumnTag,
    BlueTRCTag,
    BrdfColorimetricParameter0Tag,
    BrdfColorimetricParameter1Tag,
    BrdfColorimetricParameter2Tag,
    BrdfColorimetricParameter3Tag,
    BrdfSpectralParameter0Tag,
    BrdfSpectralParameter1Tag,
    BrdfSpectralParameter2Tag,
    BrdfSpectralParameter3Tag,
    BRDFAToB0Tag,
    BRDFAToB1Tag,
    BRDFAToB2Tag,
    BRDFAToB3Tag,
    BRDFDToB0Tag,
    BRDFDToB1Tag,
    BRDFDToB2Tag,
    BRDFDToB3Tag,
    BRDFMToB0Tag,
    BRDFMToB1Tag,
    BRDFMToB2Tag,
    BRDFMToB3Tag,
    BRDFMToS0Tag,
    BRDFMToS1Tag,
    BRDFMToS2Tag,
    BRDFMToS3Tag,
    BToA0Tag,
    BToA1Tag,
    BToA2Tag,
    BToA3Tag,
    CalibrationDateTimeTag,
    CharTargetTag,
    ChromaticAdaptationTag,
    ChromaticityTag,
    ColorEncodingParamsTag,
    ColorSpaceNameTag,
    ColorantInfoTag,
    ColorantInfoOutTag,
    ColorantOrderTag,
    ColorantOrderOutTag,
    ColorantTableTag,
    ColorantTableOutTag,
    ColorimetricIntentImageStateTag,
    CopyrightTag,
    CrdInfoTag,
    CustomToStandardPccTag,
    CxFTag,
    DataTag,
    DateTimeTag,
    DeviceMediaWhitePointTag,
    DeviceMfgDescTag,
    DeviceModelDescTag,
    DeviceSettingsTag,
    DToB0Tag,
    DToB1Tag,
    DToB2Tag,
    DToB3Tag,
    BToD0Tag,
    BToD1Tag,
    BToD2Tag,
    BToD3Tag,
    GamutTag,
    GamutBoundaryDescription0Tag,
    GamutBoundaryDescription1Tag,
    GamutBoundaryDescription2Tag,
    GamutBoundaryDescription3Tag,
    GrayTRCTag,
    GreenMatrixColumnTag,
    GreenTRCTag,
    LuminanceTag,
    MaterialDefaultValuesTag,
    MaterialTypeArrayTag,
    MToA0Tag,
    MToB0Tag,
    MToB1Tag,
    MToB2Tag,
    MToB3Tag,
    MToS0Tag,
    MToS1Tag,
    MToS2Tag,
    MToS3Tag,
    MeasurementTag,
    MediaBlackPointTag,
    MediaWhitePointTag,
    MetaDataTag,
    NamedColorTag,
    NamedColorV5Tag,
    NamedColor2Tag,
    OutputResponseTag,
    PerceptualRenderingIntentGamutTag,
    Preview0Tag,
    Preview1Tag,
    Preview2Tag,
    PrintConditionTag,
    ProfileDescriptionTag,
    ProfileSequenceDescTag,
    ProfileSequceIdTag,
    Ps2CRD0Tag,
    Ps2CRD1Tag,
    Ps2CRD2Tag,
    Ps2CRD3Tag,
    Ps2CSATag,
    Ps2RenderingIntentTag,
    RedMatrixColumnTag,
    RedTRCTag,
    ReferenceNameTag,
    SaturationRenderingIntentGamutTag,
    ScreeningDescTag,
    ScreeningTag,
    SpectralDataInfoTag,
    SpectralWhitePointTag,
    SpectralViewingConditionsTag,
    StandardToCustomPccTag,
    SurfaceMapTag,
    TechnologyTag,
    UcrBgTag,
    ViewingCondDescTag,
    ViewingConditionsTag,
    EmbeddedV5ProfileTag,
    MakeAndModelTag,
    MultilocalizedDescriptionStringTag,
    NativeDisplayInfoTag,
    VcgtTag,
    VcgpTag,
    AbsToRelTransSpaceTag,
    
);