[package]
name = "cmx"
version = "0.0.0"
description = "Rust Spectral Color Management Library"
authors = ["Gerard Harbers", "Harbers Bik LLC"]
repository = "https://github.com/harbik/cmx"
keywords = ["color_management", "icc_profiles", "iccmax"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
half = {version = "1.8", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
isolang = { version = "2.1", features = ["serde"] }
isocountry = "0.3"

[dev-dependencies]
glob = "0.3"