[package]
name = "cmx"
version = "0.0.0"
description = "Rust Spectral Color Management Library"
authors = ["Gerard Harbers", "Harbers Bik LLC"]
repository = "https://github.com/harbik/cmx"
keywords = ["color_management", "icc_profiles", "iccmax"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
chrono = "0.4"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
half = "1.8"
